/* Civic OS premium entry + role-based workspaces */
(()=>{const shell=document.getElementById("civicPortalShell"),workspace=document.getElementById("civicWorkspace");if(!shell||!workspace)return;
const views={splash:document.getElementById("civicSplashView"),auth:document.getElementById("civicAuthView"),portal:document.getElementById("civicPortalSelectView")};
const show=n=>Object.entries(views).forEach(([k,v])=>v&&v.classList.toggle("is-active",k===n));
const configs={citizen:{label:"Citizen Portal",sub:"Report, understand and track civic issues",nav:[["home","Home","house"],["report","Report","camera-plus"],["ai","Civic AI","sparkles"],["reports","My Reports","clipboard-list"],["account","Account","user-round"]]},government:{label:"Government Portal",sub:"PWD road infrastructure intelligence",nav:[["overview","Overview","layout-dashboard"],["intelligence","Intelligence","brain-circuit"],["inspections","Inspections","clipboard-check"],["roads","Roads","route"],["account","Account","user-round"]]}};
let portal="citizen",current="home";
function action(a){if(a==="report"||a==="ai"||a==="reports"){current=a;renderNav();renderPage(current)}else if(a==="legacy-report"&&window.showScreen){closeWorkspace();window.showScreen("reportScreen")}else if(a==="legacy-ai"&&typeof window.openCivicAi==="function"){closeWorkspace();window.openCivicAi()}else if(a==="legacy-issues"&&window.showScreen){closeWorkspace();window.showScreen("issuesScreen")}else if(a==="legacy-pwd"&&window.showScreen){closeWorkspace();window.showScreen("pwdIntelligenceScreen")}}
function renderPage(key){const main=document.getElementById("civicWorkspaceMain");if(!main)return;let html="";
if(portal==="citizen"){if(key==="home")html='<div class="civic-welcome"><div><span class="civic-entry-badge">CITIZEN WORKSPACE</span><h1>What needs attention today?</h1><p>Turn what you see on the street into evidence that can reach the right team.</p></div></div><div class="civic-work-grid"><section class="civic-work-card"><h3>📍 Report a road problem</h3><p>Upload evidence and let Civic OS structure the report for you.</p><div class="civic-hero-action"><div><strong>See something broken?</strong><span>Photo · location · description · AI analysis</span></div><button class="civic-work-primary" data-action="report">Start a report →</button></div><div class="civic-stat-grid"><div class="civic-stat"><strong>3</strong><span>My reports</span></div><div class="civic-stat"><strong>1</strong><span>In progress</span></div><div class="civic-stat"><strong>2</strong><span>Resolved</span></div></div></section><aside class="civic-work-card"><h3>Quick actions</h3><div class="civic-quick-grid"><button class="civic-quick" data-action="ai"><i data-lucide="sparkles"></i><span>Ask Civic AI<small>Understand a civic problem</small></span></button><button class="civic-quick" data-action="reports"><i data-lucide="clipboard-list"></i><span>My reports<small>Track submitted issues</small></span></button></div></aside></div>';
else if(key==="report")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">PWD-01 · ROAD REPORTING</span><h2>Report a road problem</h2><p>Your existing report flow keeps its AI evidence analysis, location routing and priority logic.</p><button class="civic-work-primary" data-action="legacy-report">Open report flow</button></div></div>';
else if(key==="ai")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">PWD-02 · CIVIC AI</span><h2>Ask Civic AI</h2><p>Describe what is happening naturally. Civic AI helps identify the issue, location, urgency and reporting path.</p><button class="civic-work-primary" data-action="legacy-ai">Open Civic AI</button></div></div>';
else if(key==="reports")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">YOUR ACTIVITY</span><h2>My reports</h2><p>Your submitted reports, status updates and AI evidence summaries will live here.</p><button class="civic-work-primary" data-action="legacy-issues">View current issues</button></div></div>';
else html='<div class="civic-empty-page"><div><span class="civic-entry-badge">ACCOUNT</span><h2>Your Civic profile</h2><p>Profile, notifications, privacy, AI information and account settings will be organised here.</p></div></div>';}
else {if(key==="overview")html='<div class="civic-welcome"><div><span class="civic-entry-badge">PWD COMMAND CENTER</span><h1>Road intelligence at a glance.</h1><p>Prioritise inspections using evidence, risk and repeat-failure signals.</p></div></div><div class="civic-stat-grid"><div class="civic-stat"><strong>18</strong><span>Critical</span></div><div class="civic-stat"><strong>42</strong><span>Needs inspection</span></div><div class="civic-stat"><strong>126</strong><span>Stable</span></div></div><div class="civic-work-grid" style="margin-top:18px"><section class="civic-work-card"><h3>🧠 AI priority queue</h3><p>Inspection candidates ranked by safety risk, impact, recurrence and evidence quality.</p><div class="civic-hero-action"><div><strong>View PWD intelligence</strong><span>Explainable priority · Road Passport · field brief</span></div><button class="civic-work-primary" data-action="legacy-pwd">Open intelligence →</button></div></section><aside class="civic-work-card"><h3>Inspection focus</h3><div class="civic-quick-grid"><div class="civic-quick"><i data-lucide="triangle-alert"></i><span>High-risk corridors<small>Safety and repeat-failure signals</small></span></div><div class="civic-quick"><i data-lucide="map-pin"></i><span>Active zones<small>District-level concentration</small></span></div></div></aside></div>';
else if(key==="intelligence")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">PWD-03 · DECISION INTELLIGENCE</span><h2>Prioritise with evidence.</h2><p>Your existing Road Passport and explainable priority layer stays at the centre of this workspace.</p><button class="civic-work-primary" data-action="legacy-pwd">Open PWD intelligence</button></div></div>';
else if(key==="inspections")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">FIELD WORKFLOW</span><h2>Inspection queue</h2><p>Assign inspections, capture field evidence, compare citizen evidence and record the official finding.</p></div></div>';
else if(key==="roads")html='<div class="civic-empty-page"><div><span class="civic-entry-badge">ROAD PASSPORTS</span><h2>Road asset intelligence</h2><p>Browse road segments by health, recurrence, evidence and maintenance history.</p><button class="civic-work-primary" data-action="legacy-pwd">Open road intelligence</button></div></div>';
else html='<div class="civic-empty-page"><div><span class="civic-entry-badge">OFFICER ACCOUNT</span><h2>Government workspace</h2><p>Officer profile, designation, division, permissions, reviewed reports and activity settings.</p></div></div>';}
main.innerHTML=html;main.className="civic-workspace-main "+(portal==="government"?"civic-government":"civic-citizen");main.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>action(b.dataset.action));document.getElementById("civicPortalLabel").textContent=configs[portal].label;document.getElementById("civicPortalSub").textContent=configs[portal].sub;refresh();}
function renderNav(){const n=document.getElementById("civicWorkspaceNav");n.innerHTML=configs[portal].nav.map(x=>'<button type="button" class="civic-nav-btn '+(x[0]===current?"is-active":"")+'" data-work-nav="'+x[0]+'"><i data-lucide="'+x[2]+'"></i><span>'+x[1]+"</span></button>").join("");n.querySelectorAll("[data-work-nav]").forEach(b=>b.onclick=()=>{current=b.dataset.workNav;renderNav();renderPage(current)});}
function refresh(){if(window.lucide&&window.lucide.createIcons)window.lucide.createIcons()}
function openApp(p){portal=p;current=p==="government"?"overview":"home";shell.classList.add("is-hidden");workspace.classList.add("is-active");document.body.dataset.portal=p;renderNav();renderPage(current)}
function closeWorkspace(){workspace.classList.remove("is-active")}
show("splash");setTimeout(()=>show("auth"),1300);
document.addEventListener("DOMContentLoaded",()=>{refresh();document.querySelectorAll("[data-portal]").forEach(b=>b.addEventListener("click",()=>openApp(b.dataset.portal)));document.getElementById("civicDemoEntry")?.addEventListener("click",()=>show("portal"));document.getElementById("civicBackToAuth")?.addEventListener("click",()=>show("auth"));document.getElementById("civicWorkspaceBrand")?.addEventListener("click",()=>{current=portal==="government"?"overview":"home";renderNav();renderPage(current)});document.getElementById("civicAccountButton")?.addEventListener("click",()=>{current="account";renderNav();renderPage(current)});document.getElementById("civicLoginForm")?.addEventListener("submit",e=>{e.preventDefault();show("portal")});document.querySelectorAll("[data-auth-tab]").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll("[data-auth-tab]").forEach(x=>x.classList.remove("is-active"));t.classList.add("is-active")}))});
document.addEventListener("pointermove",e=>{const b=shell.querySelector(".civic-portal-beam");if(b&&!shell.classList.contains("is-hidden")){b.style.left=e.clientX+"px";b.style.top=e.clientY+"px"}});
})();